# Generated by Django 6.0.4 on 2026-04-14 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10, verbose_name='유형')),
                ('icon', models.CharField(default='💰', max_length=10, verbose_name='아이콘')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='색상')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10, verbose_name='유형')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='내용')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역 목록',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='예산금액')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '예산',
                'verbose_name_plural': '예산 목록',
                'unique_together': {('category', 'year', 'month')},
            },
        ),
    ]
